name: Deno

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

permissions:
  contents: read

jobs:
  build-container:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
          
      - name: Build docker image
        working-directory: pingService
        run: | 
          docker build . --tag delivery-service:latest 
      
      - name: log in dockerhub
        uses: docker/login-action@v3
        with: 
          username: ${{ vars.DOCKER_USERNAME }} 
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Push container to DockerHub
        run: | 
          docker push ${{ secrets.DOCKER_USERNAME }}/ping-service:latest 
